ALTER DATABASE whitelist CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE log CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE logtypes CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE whitelist CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;